### ISSUE TITLE
각 게시글에서 Likey 버튼을 따로 fetching 하지 하지 않고 데이터 불러오게 변경하기

### ISSUE THREAD

**Issue by teddysjung** [SecretLibrary/SecretLibrary#3]
지금은 게시글마다 likey 갯수를 fetching 받게 하고있음.
그런데, 누가 버튼을 눌렀는지에 대해서 보여줄 필요가 없기 때문에 fetching 하지 않고 
게시글 정보에서 가지고 있는 likey 갯수를 보여주게 바꿔줘도 상관없음.

- likey Fetching 함수 제거

**Comment by eggplantiny** [comment]
보니까 fetching 을 하지 않으면 내가 해당 게시글에 좋아요를 눌렀는지 아닌지를 확인할 수 없음 -_-;
그대로 놔둬야할것같다...
일단 fetchComment 와 fetchLikey 를 Promise.All 로 묶어서 최소한 반응속도를 올려주는걸로 만족하자
